servers:
  cache:
    redis:
      host: localhost
      port: 6379
    memcached:
      host: localhost
      port: 11211
databases:
  influxdb:
    host: 'io.meteostation.online'
    port: 443
    ssl: true
    database: 'test'
    username: 'test'
    password: 'test'
actions:
  save:
    batch: 1800
  reboot:
    batch: 1200
    attempt: 5
scan:
  i2c: 1
  type: 'whitelist'
prefixes:
  sensors: 'devices.sensors.'
interface:
  serial:
    sensors:
      '/dev/ttyS1':
        sds011:
          baudrate: 9600
          timeout: 2
  i2c:
    displays:
      '0x27':
        hd44780:
          hd44780
    sensors:
      '0x23':
        BH1750FVI:
          bh1750
      '0x40':
        SHT21:
          sht21
      '0x76':
        BME280:
          bme280
      '0x77':
        BMP 180:
          bmp180
